import { test, expect } from "@playwright/test";
import { bookData } from "../test-data/backend/books";
import { addPurchase } from "../helpers/backend/addPurchase";
import { addBook } from "../helpers/backend/addBook";
import { updateBook } from "../helpers/backend/updateBook";
import { approvePurchase } from "../helpers/backend/approvePurchase";
import { listSpecificBook } from "../helpers/backend/listSpecificBook";
import { listSpecificUserBookPurchases } from "../helpers/backend/listSpecificUserBookPurchases";
import { listAllPurchases } from "../helpers/backend/listAllPurchases";
import { deleteBook } from "../helpers/backend/deleteBooks";

test.describe.serial('Purchases', () => {
    let admin = { id: 1}; // seeded in the db.
    let student = { id: 3 }; // seeded in the db.

    test('CT-API-023: Should allow buying a book with available stock', async ({ request }) => {
        const book = await bookData();

        const { body: book_Info } = await addBook(request, book);

        const bookInfo = { id: book_Info.id, stock: book_Info.estoque, price: book_Info.preco };

        const purchase = { usuarioId: student.id, livroId: bookInfo.id, quantidade: 2}; // Minimum stock generated by bookData() is 5;

        const totalPrice = bookInfo.price * purchase.quantidade;

        const { response, body } = await addPurchase(request, purchase);

        expect(response.status()).toBe(201);

        expect(body.status).toBe('pendente'.toUpperCase());

        expect(body.total).toBe(totalPrice);

        await deleteBook(request, book_Info.id);
    });

    test('CT-API-024: Should not allow buying book with no available stock', async ({ request }) => {
        const book = await bookData();

        const bookWithoutStock = { ...book, estoque: 0 };

        const { body: book_Info } = await addBook(request, bookWithoutStock);

        const requestedQuantity = book_Info.estoque + 1;

        const purchaseQuantityExceedingStock = { usuarioId: student.id, livroId: book_Info.id, quantidade: requestedQuantity };

        const { response, body } = await addPurchase(request, purchaseQuantityExceedingStock);

        expect(response.status()).toBe(400);

        expect(body.mensagem).toBe('Estoque insuficiente');

        await deleteBook(request, book_Info.id);
    });

    test('CT-API-025: Should approve book purchase', async ({ request }) => {
        const book = await bookData();

        const { body: book_Info } = await addBook(request, book);

        const purchase = { usuarioId: student.id, livroId: book_Info.id, quantidade: 2};

        const { body: purchase_Info } = await addPurchase(request, purchase);

        const { response, body } = await approvePurchase(request, purchase_Info.id, 'APROVADA');

        expect(response.status()).toBe(200);

        expect(body.status).toBe('APROVADA');

        const { body: updatedBook } = await listSpecificBook(request, book_Info.id);

        const currentStock = book_Info.estoque - purchase.quantidade

        expect(updatedBook.estoque).toBe(currentStock);

        await deleteBook(request, book_Info.id);
    });

    test('CT-API-026: Should cancel book purchase', async ({ request }) => {
        const book = await bookData();

        const { body: book_Info_Before } = await addBook(request, book);

        const bookBefore = book_Info_Before.estoque;

        const purchase = { usuarioId: student.id, livroId: book_Info_Before.id, quantidade: 2};

        const { body: purchase_Info } = await addPurchase(request, purchase);

        const { response, body } = await approvePurchase(request, purchase_Info.id, 'CANCELADA');

        expect(response.status()).toBe(200);

        expect(body.status).toBe('CANCELADA');

        const { body: book_Info_After } = await listSpecificBook(request, book_Info_Before.id);

        const bookAfter = book_Info_After.estoque;

        expect(bookAfter.estoque).toBe(bookBefore.estoque);

        await deleteBook(request, book_Info_After.id);
    });

    test('CT-API-027: Should list all user\'s purchases', async({ request }) => {
        const book = await bookData();

        const { body: book_Info } = await addBook(request, book);

        const purchase = { usuarioId: student.id, livroId: book_Info.id, quantidade: 2};

        const { body: purchase_Info } = await addPurchase(request, purchase);

        await approvePurchase(request, purchase_Info.id, 'APROVADA');

        const { response, body } = await listSpecificUserBookPurchases(request, student.id);

        expect(response.status()).toBe(200);

        expect(Array.isArray(body)).toBe(true);

        expect(body.length).toBeGreaterThan(0);

        body.forEach(purchase => {
            expect(purchase.usuarioId).toBe(student.id);
        })

        await deleteBook(request, book_Info.id);
    });

    test('CT-API-028: Should list purchases from all users', async ({ request }) => {
        const book = await bookData();

        const { body: book_Info } = await addBook(request, book);

        const purchase_admin = { usuarioId: admin.id, livroId: book_Info.id, quantidade: 1};
 
        const purchase_student = { usuarioId: student.id, livroId: book_Info.id, quantidade: 1};

        const { body: purchase_Admin_Info } = await addPurchase(request, purchase_admin);

        const { body: purchase_Student_Info } = await addPurchase(request, purchase_student);

        await approvePurchase(request, purchase_Admin_Info.id, 'APROVADA');

        await approvePurchase(request, purchase_Student_Info.id, 'APROVADA');
        
        const { response, body } = await listAllPurchases(request);

        expect(response.status()).toBe(200);

        expect(Array.isArray(body)).toBe(true);

        const list = body.map(purchase => purchase.usuarioId);

        const uniqueList = [...new Set(list)];

        expect(uniqueList.length).toBeGreaterThan(0);

        await deleteBook(request, book_Info.id);
    });
});